import { ORDER_LIMITS } from '@foodhubme/shared';

export const OrderPolicy = {
  MAX_LINES: ORDER_LIMITS.MAX_LINES,

  MAX_QUANTITY_PER_LINE: ORDER_LIMITS.MAX_QUANTITY_PER_LINE,

  MAX_OPTIONS_PER_LINE: ORDER_LIMITS.MAX_OPTIONS_PER_LINE,

  MAX_COMMENT_LENGTH: ORDER_LIMITS.MAX_COMMENT_LENGTH,
  MAX_ADDRESS_LENGTH: ORDER_LIMITS.MAX_ADDRESS_LENGTH,
  MAX_ADDRESS_DETAILS_LENGTH: ORDER_LIMITS.MAX_ADDRESS_DETAILS_LENGTH,

  LATITUDE_RANGE: { MIN: -90, MAX: 90 },
  LONGITUDE_RANGE: { MIN: -180, MAX: 180 },

  HISTORY_LIMIT: 50,

  PREP_MINUTES: { MIN: 1, MAX: 240 },

  CANCEL_REASON: { MIN_LENGTH: 3, MAX_LENGTH: 500 },
} as const;
