export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',

  ACCESS_DENIED: 'ACCESS_DENIED',

  LOGIN_ATTEMPTS_EXCEEDED: 'LOGIN_ATTEMPTS_EXCEEDED',

  OTP_TOO_SOON: 'OTP_TOO_SOON',

  OTP_LIMIT_EXCEEDED: 'OTP_LIMIT_EXCEEDED',

  INVALID_OTP: 'INVALID_OTP',

  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',

  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',

  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',

  INVALID_MODIFIERS: 'INVALID_MODIFIERS',

  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  ORDER_NOT_AVAILABLE: 'ORDER_NOT_AVAILABLE',

  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',

  ORDER_STATUS_CONFLICT: 'ORDER_STATUS_CONFLICT',

  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
